language: python

git:
  submodules: false

branches:
  only:
  - sources

before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key

install:
- pip install -r requirements.txt

script:
- make publish github

notification:
    email:
        on_failure: always
